spring:
  application:
    name: eureka-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/q888710631/cloud-config.git
          default-label: master
  profiles:
    active: git
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/ #eureka server地址
    register-with-eureka: true #自己是客户端，向注册中心报道
    fetch-registry: true
  instance:
    metadata-map:
      instance-id: ${spring.application.name}:${spring.application.instance_id}:${random.value}